version: '3.4'
services:
  FA3ST:
    image: fraunhoferiosb/faaast-service
    volumes:
      - ../examples/demoAAS.json:/AASEnv.json
      - ../examples/exampleConfiguration.json:/config.json
    environment:
      - faaast.model=AASEnv.json
      - faaast.config=config.json
    ports:
      - 8080:8080
    command: --no-modelValidation

