version: '3.4'
services:
  FA3ST:
    image: hansmees/faaast-no-root
    volumes:
      - ../examples/:/app/resources/
    environment:
      - faaast.model=/app/resources/demoAAS.json
      - faaast.config=/app/resources/exampleConfiguration.json
    ports:
      - 8080:8080
