version: '3.4'
services:
  FA3ST:
    image: fraunhoferiosb/faaast-service
    volumes:
      - ../examples/demoAAS.json:/app/AASEnv.json
      - ../examples/exampleConfiguration.json:/app/config.json
    environment:
      - faaast.model=/app/AASEnv.json
      - faaast.config=/app/config.json
    ports:
      - 8080:8080
