apiVersion: v1
kind: Service
metadata:
  name: {{ include "faaast-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include (printf "%s.name" .Chart.Name) . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ (index (index (default (dict "type" "ClusterIP") .Values "service")) "type") }}
  ports:
    {{- range (default (list (dict "port" 443)) .Values.endpoints) }}
    - name: https
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include (printf "%s.name" .Chart.Name) . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
