name: CVE Database Update Scheduled

on:
  schedule:
    # Every day at 4 AM UTC
    - cron: '0 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y-%m-%dT%H:%M:%S")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Restore Cache - CVE Database
      uses: actions/cache@v5
      with:
        path: |
          ~/.m2/repository/org/owasp/dependency-check-data
        key: ${{ runner.os }}-maven-owasp-cvedb-${{ steps.get-date.outputs.date }}
        restore-keys: ${{ runner.os }}-maven-owasp-cvedb

    - name: Update CVE Database
      env:
        OWASP_OSS_INDEX_USERNAME: ${{ secrets.OWASP_OSS_INDEX_USERNAME }}
        OWASP_OSS_INDEX_APIKEY: ${{ secrets.OWASP_OSS_INDEX_APIKEY }}
        NIST_NVD_API_KEY: ${{ secrets.NIST_NVD_API_KEY }}
      run: |
        mvn -B -P owasp -DnvdApiDelay=6000 --settings maven-ci-settings.xml org.owasp:dependency-check-maven:update-only
