name: Maven Build

on:
  push:
    branches:
      - main
      - feature/**
      - bugfix/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Cache maven repository
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Install Prosys SDK
      run : |
        sudo apt install p7zip-full
        curl -u "${{ secrets.OWNCLOUD_PROSYS_SHARE_ID }}:${{ secrets.OWNCLOUD_PROSYS_PASSWORD }}" ${{ secrets.OWNCLOUD_PROSYS_URL }} -o prosys.zip
        7z x prosys.zip
        cd ProsysHelper
        cd maven-integration/maven-install-helper
        mvn install
        cd ../../codegen/maven-integration/maven-install-helper
        mvn install

    - name: Build with Maven
      run: |
        mvn -B install -P ci-build -DskipTests -Dmaven.javadoc.skip=true

    - name: Maven Test
      run: |
        mvn -B verify -P ci-build -Dmaven.javadoc.skip=true

    - name: Test with Sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B verify -P ci-build org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FraunhoferIOSB_FAAAST-Service -Dmaven.javadoc.skip=true

    - name: Build Docker Image
      run: |
        mvn -B jib:dockerBuild -pl starter -Dcontainer.image.tag=${GITHUB_REF_NAME//\//-}

    - name: Push Docker Image
      if: github.ref == 'refs/heads/main'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        mvn -B jib:build -pl starter -Dcontainer.image.tag=latest
