name: Maven Pull Request Build

on:
  pull_request:
    branches:
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Cache maven repository
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: pr-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          pr-${{ runner.os }}-maven
          ${{ runner.os }}-maven

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Install Prosys SDK
      run : |
        cd ~
        sudo apt install p7zip-full
        curl --show-error --silent --user "${{ secrets.OWNCLOUD_PROSYS_SHARE_ID }}:${{ secrets.OWNCLOUD_PROSYS_PASSWORD }}" ${{ secrets.OWNCLOUD_PROSYS_URL }} --output prosys.zip
        7z x prosys.zip
        cd ProsysHelper
        cd maven-integration/maven-install-helper
        mvn -B install
        cd ../../codegen/maven-integration/maven-install-helper
        mvn -B install

    - name: Build with Maven
      run: |
        mvn -B install -P ci-build -Dmaven.javadoc.skip=true

    - name: Test with Sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B verify -P coverage sonar:sonar -Dsonar.projectKey=FraunhoferIOSB_FAAAST-Service -Dmaven.javadoc.skip=true
